var DATAEXCEL = [
  {
    Cluster: 90909,
    qtdClientesTotal: 291,
    qtdClientesNovos: 282,
    analiseTemporalMedia: 1.0,
    analiseTemporalMin: 1.0,
    analiseTemporalMax: 1.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 109.45,
    analiseMonetariaTicketMin: 9.1,
    analiseMonetariaTicketMax: 199.99,
    cltv: 109.45,
    volumeDeVendas: "31.850.66",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Casuais / Novos entrantes",
    color: "#16a085",
  },
  {
    Cluster: 90915,
    qtdClientesTotal: 270,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 2.0,
    analiseTemporalMin: 2.0,
    analiseTemporalMax: 2.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 103.82,
    analiseMonetariaTicketMin: 24.99,
    analiseMonetariaTicketMax: 199.8,
    cltv: 103.82,
    volumeDeVendas: "28.030.30",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Em risco",
    color: "#e74c3c",
  },
  {
    Cluster: 0,
    qtdClientesTotal: 265,
    qtdClientesNovos: 262,
    analiseTemporalMedia: 1.0,
    analiseTemporalMin: 1.0,
    analiseTemporalMax: 1.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 278.91,
    analiseMonetariaTicketMin: 206.0,
    analiseMonetariaTicketMax: 348.79,
    cltv: 278.91,
    volumeDeVendas: "73.911.60",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Promissor",
    color: "#f1c40f",
  },
  {
    Cluster: 24,
    qtdClientesTotal: 238,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 2.0,
    analiseTemporalMin: 2.0,
    analiseTemporalMax: 2.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 276.52,
    analiseMonetariaTicketMin: 201.8,
    analiseMonetariaTicketMax: 344.99,
    cltv: 276.52,
    volumeDeVendas: "65.810.87",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Em risco",
    color: "#e74c3c",
  },
  {
    Cluster: 16,
    qtdClientesTotal: 229,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 3.0,
    analiseTemporalMin: 3.0,
    analiseTemporalMax: 3.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 91.72,
    analiseMonetariaTicketMin: 11.9,
    analiseMonetariaTicketMax: 152.0,
    cltv: 91.72,
    volumeDeVendas: "21.004.51",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Perdido",
    color: "#7f8c8d",
  },
  {
    Cluster: 401,
    qtdClientesTotal: 216,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 4.0,
    analiseTemporalMin: 4.0,
    analiseTemporalMax: 4.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 110.87,
    analiseMonetariaTicketMin: 36.4,
    analiseMonetariaTicketMax: 199.8,
    cltv: 110.87,
    volumeDeVendas: "23.947.89",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Perdido",
    color: "#7f8c8d",
  },
  {
    Cluster: 14,
    qtdClientesTotal: 127,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 3.48,
    analiseTemporalMin: 3.0,
    analiseTemporalMax: 4.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 321.6,
    analiseMonetariaTicketMin: 262.99,
    analiseMonetariaTicketMax: 349.99,
    cltv: 321.6,
    volumeDeVendas: "40.842.94",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Hibernando",
    color: "#34495e",
  },
  {
    Cluster: 28,
    qtdClientesTotal: 96,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 3.0,
    analiseTemporalMin: 3.0,
    analiseTemporalMax: 3.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 239.09,
    analiseMonetariaTicketMin: 201.0,
    analiseMonetariaTicketMax: 303.2,
    cltv: 239.09,
    volumeDeVendas: "22.953.07",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Hibernando",
    color: "#34495e",
  },
  {
    Cluster: 90914,
    qtdClientesTotal: 74,
    qtdClientesNovos: 74,
    analiseTemporalMedia: 1.0,
    analiseTemporalMin: 1.0,
    analiseTemporalMax: 1.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 448.29,
    analiseMonetariaTicketMin: 351.39,
    analiseMonetariaTicketMax: 609.28,
    cltv: 448.29,
    volumeDeVendas: "33.173.42",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Alto Potencial",
    color: "#3498db",
  },
  {
    Cluster: 4,
    qtdClientesTotal: 57,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 4.0,
    analiseTemporalMin: 4.0,
    analiseTemporalMax: 4.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 219.66,
    analiseMonetariaTicketMin: 200.0,
    analiseMonetariaTicketMax: 254.89,
    cltv: 219.66,
    volumeDeVendas: "12.520.56",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Hibernando",
    color: "#34495e",
  },
  {
    Cluster: 2801,
    qtdClientesTotal: 52,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 3.0,
    analiseTemporalMin: 3.0,
    analiseTemporalMax: 3.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 166.52,
    analiseMonetariaTicketMin: 152.72,
    analiseMonetariaTicketMax: 199.8,
    cltv: 166.52,
    volumeDeVendas: "8.658.85",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Perdido",
    color: "#7f8c8d",
  },
  {
    Cluster: 11,
    qtdClientesTotal: 52,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 3.4,
    analiseTemporalMin: 3.0,
    analiseTemporalMax: 4.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 560.13,
    analiseMonetariaTicketMin: 444.89,
    analiseMonetariaTicketMax: 753.9,
    cltv: 560.13,
    volumeDeVendas: "29.126.55",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Recuperar",
    color: "#22a6b3",
  },
  {
    Cluster: 90917,
    qtdClientesTotal: 50,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 2.0,
    analiseTemporalMin: 2.0,
    analiseTemporalMax: 2.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 463.24,
    analiseMonetariaTicketMin: 360.19,
    analiseMonetariaTicketMax: 583.79,
    cltv: 463.24,
    volumeDeVendas: "23.161.96",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Em risco",
    color: "#e74c3c",
  },
  {
    Cluster: 10001,
    qtdClientesTotal: 35,
    qtdClientesNovos: 8,
    analiseTemporalMedia: 1.0,
    analiseTemporalMin: 1.0,
    analiseTemporalMax: 1.0,
    analiseFidelidadeMedia: 2.0,
    analiseFidelidadeMin: 2.0,
    analiseFidelidadeMax: 2.0,
    analiseMonetariaTicketMedio: 129.77,
    analiseMonetariaTicketMin: 53.13,
    analiseMonetariaTicketMax: 197.3,
    cltv: 259.54,
    volumeDeVendas: "9.083.80",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Promissor",
    color: "#f1c40f",
  },
  {
    Cluster: 90916,
    qtdClientesTotal: 32,
    qtdClientesNovos: 9,
    analiseTemporalMedia: 1.0,
    analiseTemporalMin: 1.0,
    analiseTemporalMax: 1.0,
    analiseFidelidadeMedia: 2.0,
    analiseFidelidadeMin: 2.0,
    analiseFidelidadeMax: 2.0,
    analiseMonetariaTicketMedio: 268.36,
    analiseMonetariaTicketMin: 204.75,
    analiseMonetariaTicketMax: 349.99,
    cltv: 536.72,
    volumeDeVendas: "17.174.88",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Promissor",
    color: "#f1c40f",
  },
  {
    Cluster: 1402,
    qtdClientesTotal: 30,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 3.53,
    analiseTemporalMin: 3.0,
    analiseTemporalMax: 4.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 391.14,
    analiseMonetariaTicketMin: 352.49,
    analiseMonetariaTicketMax: 450.6,
    cltv: 391.14,
    volumeDeVendas: "11.734.20",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Recuperar",
    color: "#22a6b3",
  },
  {
    Cluster: 32,
    qtdClientesTotal: 28,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 2.0,
    analiseTemporalMin: 2.0,
    analiseTemporalMax: 2.0,
    analiseFidelidadeMedia: 2.0,
    analiseFidelidadeMin: 2.0,
    analiseFidelidadeMax: 2.0,
    analiseMonetariaTicketMedio: 261.79,
    analiseMonetariaTicketMin: 203.8,
    analiseMonetariaTicketMax: 347.49,
    cltv: 523.57,
    volumeDeVendas: "14.660.02",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Em risco",
    color: "#e74c3c",
  },
  {
    Cluster: 90918,
    qtdClientesTotal: 25,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 2.0,
    analiseTemporalMin: 2.0,
    analiseTemporalMax: 2.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 891.23,
    analiseMonetariaTicketMin: 654.99,
    analiseMonetariaTicketMax: 1905.85,
    cltv: 891.23,
    volumeDeVendas: "22.280.75",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Em risco",
    color: "#e74c3c",
  },
  {
    Cluster: 90913,
    qtdClientesTotal: 23,
    qtdClientesNovos: 23,
    analiseTemporalMedia: 1.0,
    analiseTemporalMin: 1.0,
    analiseTemporalMax: 1.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 980.21,
    analiseMonetariaTicketMin: 629.1,
    analiseMonetariaTicketMax: 1939.87,
    cltv: 980.21,
    volumeDeVendas: "22.544.94",
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Alto Potencial",
    color: "#3498db",
  },
  {
    Cluster: 90905,
    qtdClientesTotal: 20,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 3.4,
    analiseTemporalMin: 3.0,
    analiseTemporalMax: 4.0,
    analiseFidelidadeMedia: 1.0,
    analiseFidelidadeMin: 1.0,
    analiseFidelidadeMax: 1.0,
    analiseMonetariaTicketMedio: 1134.29,
    analiseMonetariaTicketMin: 778.98,
    analiseMonetariaTicketMax: 2049.24,
    cltv: 1134.29,
    volumeDeVendas: 22685.86,
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Recuperar",
    color: "#22a6b3",
  },
  {
    Cluster: 15001,
    qtdClientesTotal: 17,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 3.12,
    analiseTemporalMin: 3.0,
    analiseTemporalMax: 4.0,
    analiseFidelidadeMedia: 2.0,
    analiseFidelidadeMin: 2.0,
    analiseFidelidadeMax: 2.0,
    analiseMonetariaTicketMedio: 132.56,
    analiseMonetariaTicketMin: 54.0,
    analiseMonetariaTicketMax: 197.2,
    cltv: 265.11,
    volumeDeVendas: 4506.93,
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Hibernando",
    color: "#34495e",
  },
  {
    Cluster: 32001,
    qtdClientesTotal: 16,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 2.0,
    analiseTemporalMin: 2.0,
    analiseTemporalMax: 2.0,
    analiseFidelidadeMedia: 2.0,
    analiseFidelidadeMin: 2.0,
    analiseFidelidadeMax: 2.0,
    analiseMonetariaTicketMedio: 142.06,
    analiseMonetariaTicketMin: 54.0,
    analiseMonetariaTicketMax: 199.8,
    cltv: 284.12,
    volumeDeVendas: 4545.93,
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Em risco",
    color: "#e74c3c",
  },
  {
    Cluster: 15,
    qtdClientesTotal: 12,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 3.25,
    analiseTemporalMin: 3.0,
    analiseTemporalMax: 4.0,
    analiseFidelidadeMedia: 2.0,
    analiseFidelidadeMin: 2.0,
    analiseFidelidadeMax: 2.0,
    analiseMonetariaTicketMedio: 259.28,
    analiseMonetariaTicketMin: 222.49,
    analiseMonetariaTicketMax: 329.99,
    cltv: 518.55,
    volumeDeVendas: 6222.64,
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Recuperar",
    color: "#22a6b3",
  },
  {
    Cluster: 90911,
    qtdClientesTotal: 12,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 1.0,
    analiseTemporalMin: 1.0,
    analiseTemporalMax: 1.0,
    analiseFidelidadeMedia: 4.5,
    analiseFidelidadeMin: 3.0,
    analiseFidelidadeMax: 8.0,
    analiseMonetariaTicketMedio: 262.53,
    analiseMonetariaTicketMin: 209.71,
    analiseMonetariaTicketMax: 343.32,
    cltv: 1181.39,
    volumeDeVendas: 14146.39,
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Cliente Fiel",
    color: "#9b59b6",
  },
  {
    Cluster: 90919,
    qtdClientesTotal: 11,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 2.0,
    analiseTemporalMin: 2.0,
    analiseTemporalMax: 2.0,
    analiseFidelidadeMedia: 2.0,
    analiseFidelidadeMin: 2.0,
    analiseFidelidadeMax: 2.0,
    analiseMonetariaTicketMedio: 524.09,
    analiseMonetariaTicketMin: 358.89,
    analiseMonetariaTicketMax: 805.1,
    cltv: 1048.17,
    volumeDeVendas: 11529.85,
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Em risco",
    color: "#e74c3c",
  },
  {
    Cluster: 90912,
    qtdClientesTotal: 11,
    qtdClientesNovos: 1,
    analiseTemporalMedia: 1.0,
    analiseTemporalMin: 1.0,
    analiseTemporalMax: 1.0,
    analiseFidelidadeMedia: 5.36,
    analiseFidelidadeMin: 3.0,
    analiseFidelidadeMax: 11.0,
    analiseMonetariaTicketMedio: 464.0,
    analiseMonetariaTicketMin: 355.0,
    analiseMonetariaTicketMax: 853.12,
    cltv: 2488.73,
    volumeDeVendas: 29381.74,
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "VIP",
    color: "#2d3436",
  },
  {
    Cluster: 90907,
    qtdClientesTotal: 10,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 3.3,
    analiseTemporalMin: 3.0,
    analiseTemporalMax: 4.0,
    analiseFidelidadeMedia: 2.0,
    analiseFidelidadeMin: 2.0,
    analiseFidelidadeMax: 2.0,
    analiseMonetariaTicketMedio: 777.29,
    analiseMonetariaTicketMin: 362.0,
    analiseMonetariaTicketMax: 2480.0,
    cltv: 1554.57,
    volumeDeVendas: 15545.7,
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Recuperar",
    color: "#22a6b3",
  },
  {
    Cluster: 90910,
    qtdClientesTotal: 10,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 1.0,
    analiseTemporalMin: 1.0,
    analiseTemporalMax: 1.0,
    analiseFidelidadeMedia: 3.9,
    analiseFidelidadeMin: 3.0,
    analiseFidelidadeMax: 6.0,
    analiseMonetariaTicketMedio: 162.65,
    analiseMonetariaTicketMin: 96.26,
    analiseMonetariaTicketMax: 199.71,
    cltv: 634.35,
    volumeDeVendas: 6159.45,
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Cliente Fiel",
    color: "#9b59b6",
  },
  {
    Cluster: 21001,
    qtdClientesTotal: 9,
    qtdClientesNovos: 4,
    analiseTemporalMedia: 1.0,
    analiseTemporalMin: 1.0,
    analiseTemporalMax: 1.0,
    analiseFidelidadeMedia: 2.0,
    analiseFidelidadeMin: 2.0,
    analiseFidelidadeMax: 2.0,
    analiseMonetariaTicketMedio: 473.08,
    analiseMonetariaTicketMin: 389.49,
    analiseMonetariaTicketMax: 613.24,
    cltv: 946.15,
    volumeDeVendas: 8515.35,
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Alto Potencial",
    color: "#3498db",
  },
  {
    Cluster: 90901,
    qtdClientesTotal: 6,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 2.0,
    analiseTemporalMin: 2.0,
    analiseTemporalMax: 2.0,
    analiseFidelidadeMedia: 3.33,
    analiseFidelidadeMin: 3.0,
    analiseFidelidadeMax: 5.0,
    analiseMonetariaTicketMedio: 257.82,
    analiseMonetariaTicketMin: 217.07,
    analiseMonetariaTicketMax: 313.29,
    cltv: 859.38,
    volumeDeVendas: 5194.57,
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Em risco",
    color: "#e74c3c",
  },
  {
    Cluster: 801,
    qtdClientesTotal: 4,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 2.0,
    analiseTemporalMin: 2.0,
    analiseTemporalMax: 2.0,
    analiseFidelidadeMedia: 3.0,
    analiseFidelidadeMin: 3.0,
    analiseFidelidadeMax: 3.0,
    analiseMonetariaTicketMedio: 152.71,
    analiseMonetariaTicketMin: 140.26,
    analiseMonetariaTicketMax: 166.06,
    cltv: 458.14,
    volumeDeVendas: 1832.54,
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Em risco",
    color: "#e74c3c",
  },
  {
    Cluster: 90903,
    qtdClientesTotal: 3,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 3.0,
    analiseTemporalMin: 3.0,
    analiseTemporalMax: 3.0,
    analiseFidelidadeMedia: 4.67,
    analiseFidelidadeMin: 3.0,
    analiseFidelidadeMax: 8.0,
    analiseMonetariaTicketMedio: 428.36,
    analiseMonetariaTicketMin: 356.23,
    analiseMonetariaTicketMax: 565.08,
    cltv: 1999.01,
    volumeDeVendas: 5636.36,
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Recuperar",
    color: "#22a6b3",
  },
  {
    Cluster: 90904,
    qtdClientesTotal: 2,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 2.0,
    analiseTemporalMin: 2.0,
    analiseTemporalMax: 2.0,
    analiseFidelidadeMedia: 5.5,
    analiseFidelidadeMin: 3.0,
    analiseFidelidadeMax: 8.0,
    analiseMonetariaTicketMedio: 423.56,
    analiseMonetariaTicketMin: 355.26,
    analiseMonetariaTicketMax: 491.86,
    cltv: 2329.58,
    volumeDeVendas: 5000.65,
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Não posso perder",
    color: "#e67e22",
  },
  {
    Cluster: 90902,
    qtdClientesTotal: 2,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 3.0,
    analiseTemporalMin: 3.0,
    analiseTemporalMax: 3.0,
    analiseFidelidadeMedia: 3.5,
    analiseFidelidadeMin: 3.0,
    analiseFidelidadeMax: 4.0,
    analiseMonetariaTicketMedio: 271.17,
    analiseMonetariaTicketMin: 206.5,
    analiseMonetariaTicketMax: 335.83,
    cltv: 949.08,
    volumeDeVendas: 1833.46,
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Recuperar",
    color: "#22a6b3",
  },
  {
    Cluster: 17,
    qtdClientesTotal: 1,
    qtdClientesNovos: 0,
    analiseTemporalMedia: 3.0,
    analiseTemporalMin: 3.0,
    analiseTemporalMax: 3.0,
    analiseFidelidadeMedia: 5.0,
    analiseFidelidadeMin: 5.0,
    analiseFidelidadeMax: 5.0,
    analiseMonetariaTicketMedio: 193.58,
    analiseMonetariaTicketMin: 193.58,
    analiseMonetariaTicketMax: 193.58,
    cltv: 967.9,
    volumeDeVendas: 967.9,
    caracteristicasPositivo: "",
    caracteristicasNegativo: "",
    Interpretacao: "Recuperar",
    color: "#22a6b3",
  },
];
